[build-system]
requires = ["setuptools", "wheel", "cython==3.0.12"]

[tool.cibuildwheel]
build = "cp313* cp314*"
skip = "*musllinux* cp313t* cp314t*"
archs = "auto64"
test-command = "python -m cypari.test"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
