[build-system]
requires = ["setuptools", "wheel", "cython==3.0.11"]

[tool.cibuildwheel]
build = "cp311* cp313*"
skip = "*musllinux* cp313t* cp314t* cp314*"
archs = "auto64"
test-command = "python -m cypari.test"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
