[build-system]
requires = ["setuptools", "wheel"]

[tool.cibuildwheel]
build = "cp38* cp39* cp310* cp311* cp312* cp313*"
skip = "*musllinux* cp313t* cp314t*"
archs = "auto64"
test-command = "python -m cypari.test"
