[build-system]
requires = ["setuptools", "wheel", "cython==3.0.12"]

[tool.cibuildwheel]
build = "cp38* cp39* cp310* cp311* cp312* cp313* cp314*"
skip = "*musllinux* cp313t* cp314t*"
archs = "auto64"
test-command = "python -m cypari.test"
